# Generated by Django 3.1.3 on 2022-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
